import { LearningCategory } from './types'

export const learningCategories: LearningCategory[] = [
  {
    id: 'alphabet',
    icon: '🔤',
    title: '26个字母',
    description: '学习英文字母和发音，点击就能听',
    color: '#FF6B9D',
    type: 'vocab',
    items: [
      { id: 'la', title: 'A', englishTitle: 'Apple', image: '🍎', pronunciation: '/eɪ/' },
      { id: 'lb', title: 'B', englishTitle: 'Ball', image: '⚽', pronunciation: '/biː/' },
      { id: 'lc', title: 'C', englishTitle: 'Cat', image: '🐱', pronunciation: '/siː/' },
      { id: 'ld', title: 'D', englishTitle: 'Dog', image: '🐶', pronunciation: '/diː/' },
      { id: 'le', title: 'E', englishTitle: 'Egg', image: '🥚', pronunciation: '/iː/' },
      { id: 'lf', title: 'F', englishTitle: 'Fish', image: '🐠', pronunciation: '/ɛf/' },
      { id: 'lg', title: 'G', englishTitle: 'Green', image: '💚', pronunciation: '/dʒiː/' },
      { id: 'lh', title: 'H', englishTitle: 'House', image: '🏠', pronunciation: '/eɪtʃ/' },
      { id: 'li', title: 'I', englishTitle: 'Ice Cream', image: '🍦', pronunciation: '/aɪ/' },
      { id: 'lj', title: 'J', englishTitle: 'Jump', image: '🤸', pronunciation: '/dʒeɪ/' },
      { id: 'lk', title: 'K', englishTitle: 'King', image: '👑', pronunciation: '/keɪ/' },
      { id: 'll', title: 'L', englishTitle: 'Lion', image: '🦁', pronunciation: '/ɛl/' },
      { id: 'lm', title: 'M', englishTitle: 'Monkey', image: '🐵', pronunciation: '/ɛm/' },
      { id: 'ln', title: 'N', englishTitle: 'Nose', image: '👃', pronunciation: '/ɛn/' },
      { id: 'lo', title: 'O', englishTitle: 'Orange', image: '🍊', pronunciation: '/oʊ/' },
      { id: 'lp', title: 'P', englishTitle: 'Penguin', image: '🐧', pronunciation: '/piː/' },
      { id: 'lq', title: 'Q', englishTitle: 'Queen', image: '👸', pronunciation: '/kjuː/' },
      { id: 'lr', title: 'R', englishTitle: 'Rabbit', image: '🐰', pronunciation: '/ɑːr/' },
      { id: 'ls', title: 'S', englishTitle: 'Sun', image: '☀️', pronunciation: '/ɛs/' },
      { id: 'lt', title: 'T', englishTitle: 'Tiger', image: '🐯', pronunciation: '/tiː/' },
      { id: 'lu', title: 'U', englishTitle: 'Umbrella', image: '☂️', pronunciation: '/juː/' },
      { id: 'lv', title: 'V', englishTitle: 'Violin', image: '🎻', pronunciation: '/viː/' },
      { id: 'lw', title: 'W', englishTitle: 'Water', image: '💧', pronunciation: '/ˈdʌbəljuː/' },
      { id: 'lx', title: 'X', englishTitle: 'Xylophone', image: '🎵', pronunciation: '/ɛks/' },
      { id: 'ly', title: 'Y', englishTitle: 'Yellow', image: '💛', pronunciation: '/waɪ/' },
      { id: 'lz', title: 'Z', englishTitle: 'Zebra', image: '🦓', pronunciation: '/zɛd/' },
    ]
  },
  {
    id: 'animals',
    icon: '🦁',
    title: '动物篇',
    description: '学习44种动物的英文名称和科普知识',
    color: '#FF6B6B',
    type: 'vocab',
    items: [
      { id: 'a01', title: '猫', englishTitle: 'Cat', image: '🐱', pronunciation: '/kæt/' },
      { id: 'a02', title: '狗', englishTitle: 'Dog', image: '🐶', pronunciation: '/dɔːɡ/' },
      { id: 'a03', title: '长颈鹿', englishTitle: 'Giraffe', image: '🦒', pronunciation: '/dʒɪˈræf/' },
      { id: 'a04', title: '鲨鱼', englishTitle: 'Shark', image: '🦈', pronunciation: '/ʃɑːrk/' },
      { id: 'a05', title: '青蛙', englishTitle: 'Frog', image: '🐸', pronunciation: '/frɒɡ/' },
      { id: 'a06', title: '火烈鸟', englishTitle: 'Flamingo', image: '🦩', pronunciation: '/fləˈmɪŋɡoʊ/' },
      { id: 'a07', title: '鸡', englishTitle: 'Chicken', image: '🐔', pronunciation: '/ˈtʃɪkɪn/' },
      { id: 'a08', title: '鸵鸟', englishTitle: 'Ostrich', image: '🦤', pronunciation: '/ˈɒstrɪtʃ/' },
      { id: 'a09', title: '鸭子', englishTitle: 'Duck', image: '🦆', pronunciation: '/dʌk/' },
      { id: 'a10', title: '小鸡', englishTitle: 'Chick', image: '🐥', pronunciation: '/tʃɪk/' },
      { id: 'a11', title: '河马', englishTitle: 'Hippo', image: '🦛', pronunciation: '/ˈhɪpoʊ/' },
      { id: 'a12', title: '大象', englishTitle: 'Elephant', image: '🐘', pronunciation: '/ˈɛlɪfənt/' },
      { id: 'a13', title: '鲸鱼', englishTitle: 'Whale', image: '🐋', pronunciation: '/weɪl/' },
      { id: 'a14', title: '犀牛', englishTitle: 'Rhino', image: '🦏', pronunciation: '/ˈraɪnoʊ/' },
      { id: 'a15', title: '牛', englishTitle: 'Cow', image: '🐄', pronunciation: '/kaʊ/' },
      { id: 'a16', title: '兔子', englishTitle: 'Rabbit', image: '🐰', pronunciation: '/ˈræbɪt/' },
      { id: 'a17', title: '马', englishTitle: 'Horse', image: '🐴', pronunciation: '/hɔːrs/' },
      { id: 'a18', title: '鹅', englishTitle: 'Goose', image: '🪿', pronunciation: '/ɡuːs/' },
      { id: 'a19', title: '章鱼', englishTitle: 'Octopus', image: '🐙', pronunciation: '/ˈɒktəpəs/' },
      { id: 'a20', title: '蚊子', englishTitle: 'Mosquito', image: '🦟', pronunciation: '/məˈskiːtoʊ/' },
      { id: 'a21', title: '熊猫', englishTitle: 'Panda', image: '🐼', pronunciation: '/ˈpændə/' },
      { id: 'a22', title: '北极熊', englishTitle: 'Polar Bear', image: '🐻‍❄️', pronunciation: '/ˈpoʊlər ber/' },
      { id: 'a23', title: '企鹅', englishTitle: 'Penguin', image: '🐧', pronunciation: '/ˈpɛŋɡwɪn/' },
      { id: 'a24', title: '猪', englishTitle: 'Pig', image: '🐷', pronunciation: '/pɪɡ/' },
      { id: 'a26', title: '老虎', englishTitle: 'Tiger', image: '🐯', pronunciation: '/ˈtaɪɡər/' },
      { id: 'a27', title: '狮子', englishTitle: 'Lion', image: '🦁', pronunciation: '/ˈlaɪən/' },
      { id: 'a28', title: '豹子', englishTitle: 'Leopard', image: '🐆', pronunciation: '/ˈlɛpərd/' },
      { id: 'a30', title: '袋鼠', englishTitle: 'Kangaroo', image: '🦘', pronunciation: '/ˌkæŋɡəˈruː/' },
      { id: 'a32', title: '蝴蝶', englishTitle: 'Butterfly', image: '🦋', pronunciation: '/ˈbʌtərflaɪ/' },
      { id: 'a33', title: '猴子', englishTitle: 'Monkey', image: '🐵', pronunciation: '/ˈmʌŋki/' },
      { id: 'a34', title: '海龟', englishTitle: 'Sea Turtle', image: '🐢', pronunciation: '/siː ˈtɜːrtl/' },
      { id: 'a36', title: '狼', englishTitle: 'Wolf', image: '🐺', pronunciation: '/wʊlf/' },
      { id: 'a37', title: '斑马', englishTitle: 'Zebra', image: '🦓', pronunciation: '/ˈziːbrə/' },
      { id: 'a38', title: '猫头鹰', englishTitle: 'Owl', image: '🦉', pronunciation: '/aʊl/' },
      { id: 'a43', title: '考拉', englishTitle: 'Koala', image: '🐨', pronunciation: '/koʊˈɑːlə/' },
    ]
  },
  {
    id: 'fruits',
    icon: '🍎',
    title: '果蔬篇',
    description: '学习36种水果蔬菜的英文名称和科普知识',
    color: '#4ECDC4',
    type: 'vocab',
    items: [
      { id: 'f01', title: '香蕉', englishTitle: 'Banana', image: '🍌', pronunciation: '/bəˈnænə/' },
      { id: 'f02', title: '西瓜', englishTitle: 'Watermelon', image: '🍉', pronunciation: '/ˈwɔːtərmelən/' },
      { id: 'f03', title: '草莓', englishTitle: 'Strawberry', image: '🍓', pronunciation: '/ˈstrɔːberi/' },
      { id: 'f04', title: '芒果', englishTitle: 'Mango', image: '🥭', pronunciation: '/ˈmæŋɡoʊ/' },
      { id: 'f05', title: '葡萄', englishTitle: 'Grape', image: '🍇', pronunciation: '/ɡreɪp/' },
      { id: 'f06', title: '柠檬', englishTitle: 'Lemon', image: '🍋', pronunciation: '/ˈlɛmən/' },
      { id: 'f07', title: '苹果', englishTitle: 'Apple', image: '🍎', pronunciation: '/ˈæpl/' },
      { id: 'f08', title: '蓝莓', englishTitle: 'Blueberry', image: '🫐', pronunciation: '/ˈbluːberi/' },
      { id: 'f09', title: '菠萝', englishTitle: 'Pineapple', image: '🍍', pronunciation: '/ˈpaɪnæpl/' },
      { id: 'f11', title: '樱桃', englishTitle: 'Cherry', image: '🍒', pronunciation: '/ˈtʃɛri/' },
      { id: 'f12', title: '桃子', englishTitle: 'Peach', image: '🍑', pronunciation: '/piːtʃ/' },
      { id: 'f13', title: '橙子', englishTitle: 'Orange', image: '🍊', pronunciation: '/ˈɔːrɪndʒ/' },
      { id: 'f14', title: '梨', englishTitle: 'Pear', image: '🍐', pronunciation: '/per/' },
      { id: 'f16', title: '西兰花', englishTitle: 'Broccoli', image: '🥦', pronunciation: '/ˈbrɒkəli/' },
      { id: 'f17', title: '黄瓜', englishTitle: 'Cucumber', image: '🥒', pronunciation: '/ˈkjuːkʌmbər/' },
      { id: 'f18', title: '番茄', englishTitle: 'Tomato', image: '🍅', pronunciation: '/təˈmeɪtoʊ/' },
      { id: 'f19', title: '土豆', englishTitle: 'Potato', image: '🥔', pronunciation: '/pəˈteɪtoʊ/' },
      { id: 'f23', title: '玉米', englishTitle: 'Corn', image: '🌽', pronunciation: '/kɔːrn/' },
    ]
  },
  {
    id: 'food',
    icon: '🍔',
    title: '食物',
    description: '学习常见食物的英文名称',
    color: '#E67E22',
    type: 'vocab',
    items: [
      { id: 'fd01', title: '米饭', englishTitle: 'Rice', image: '🍚', pronunciation: '/raɪs/' },
      { id: 'fd02', title: '面条', englishTitle: 'Noodles', image: '🍜', pronunciation: '/ˈnuːdəlz/' },
      { id: 'fd03', title: '面包', englishTitle: 'Bread', image: '🍞', pronunciation: '/bred/' },
      { id: 'fd04', title: '牛奶', englishTitle: 'Milk', image: '🥛', pronunciation: '/mɪlk/' },
      { id: 'fd05', title: '鸡蛋', englishTitle: 'Egg', image: '🥚', pronunciation: '/ɛɡ/' },
      { id: 'fd06', title: '蛋糕', englishTitle: 'Cake', image: '🎂', pronunciation: '/keɪk/' },
      { id: 'fd07', title: '冰淇淋', englishTitle: 'Ice Cream', image: '🍦', pronunciation: '/aɪs kriːm/' },
      { id: 'fd08', title: '糖果', englishTitle: 'Candy', image: '🍬', pronunciation: '/ˈkændi/' },
      { id: 'fd09', title: '饼干', englishTitle: 'Cookie', image: '🍪', pronunciation: '/ˈkʊki/' },
      { id: 'fd10', title: '果汁', englishTitle: 'Juice', image: '🧃', pronunciation: '/dʒuːs/' },
      { id: 'fd11', title: '茶', englishTitle: 'Tea', image: '🍵', pronunciation: '/tiː/' },
      { id: 'fd12', title: '水', englishTitle: 'Water', image: '💧', pronunciation: '/ˈwɔːtər/' },
      { id: 'fd13', title: '披萨', englishTitle: 'Pizza', image: '🍕', pronunciation: '/ˈpiːtsə/' },
      { id: 'fd14', title: '汉堡', englishTitle: 'Hamburger', image: '🍔', pronunciation: '/ˈhæmbɜːrɡər/' },
      { id: 'fd15', title: '热狗', englishTitle: 'Hot Dog', image: '🌭', pronunciation: '/hɒt dɔːɡ/' },
      { id: 'fd16', title: '鱼肉', englishTitle: 'Fish', image: '🐟', pronunciation: '/fɪʃ/' },
      { id: 'fd17', title: '鸡肉', englishTitle: 'Chicken', image: '🍗', pronunciation: '/ˈtʃɪkɪn/' },
    ]
  },
  {
    id: 'vehicles',
    icon: '🚗',
    title: '车辆篇',
    description: '学习20种车辆的英文名称和科普知识',
    color: '#45B7D1',
    type: 'vocab',
    items: [
      { id: 'v01', title: '消防车', englishTitle: 'Fire Truck', image: '🚒', pronunciation: '/faɪr trʌk/' },
      { id: 'v02', title: '救护车', englishTitle: 'Ambulance', image: '🚑', pronunciation: '/ˈæmbjələns/' },
      { id: 'v03', title: '警车', englishTitle: 'Police Car', image: '🚔', pronunciation: '/pəˈliːs kɑːr/' },
      { id: 'v04', title: '挖掘机', englishTitle: 'Excavator', image: '🚜', pronunciation: '/ˈɛkskəveɪtər/' },
      { id: 'v14', title: '飞机', englishTitle: 'Airplane', image: '✈️', pronunciation: '/ˈɛrpleɪn/' },
      { id: 'v15', title: '高铁', englishTitle: 'High-speed Train', image: '🚄', pronunciation: '/haɪ spiːd treɪn/' },
      { id: 'v16', title: '公交车', englishTitle: 'Bus', image: '🚌', pronunciation: '/bʌs/' },
      { id: 'v17', title: '汽车', englishTitle: 'Car', image: '🚗', pronunciation: '/kɑːr/' },
      { id: 'v20', title: '直升机', englishTitle: 'Helicopter', image: '🚁', pronunciation: '/ˈhɛlɪkɒptər/' },
    ]
  },
  {
    id: 'numbers',
    icon: '🔢',
    title: '数字',
    description: '学习1到20的英文数字',
    color: '#2ECC71',
    type: 'vocab',
    items: [
      { id: 'n01', title: '1', englishTitle: 'One', image: '1️⃣', pronunciation: '/wʌn/' },
      { id: 'n02', title: '2', englishTitle: 'Two', image: '2️⃣', pronunciation: '/tuː/' },
      { id: 'n03', title: '3', englishTitle: 'Three', image: '3️⃣', pronunciation: '/θriː/' },
      { id: 'n04', title: '4', englishTitle: 'Four', image: '4️⃣', pronunciation: '/fɔːr/' },
      { id: 'n05', title: '5', englishTitle: 'Five', image: '5️⃣', pronunciation: '/faɪv/' },
      { id: 'n06', title: '6', englishTitle: 'Six', image: '6️⃣', pronunciation: '/sɪks/' },
      { id: 'n07', title: '7', englishTitle: 'Seven', image: '7️⃣', pronunciation: '/ˈsɛvən/' },
      { id: 'n08', title: '8', englishTitle: 'Eight', image: '8️⃣', pronunciation: '/eɪt/' },
      { id: 'n09', title: '9', englishTitle: 'Nine', image: '9️⃣', pronunciation: '/naɪn/' },
      { id: 'n10', title: '10', englishTitle: 'Ten', image: '🔟', pronunciation: '/tɛn/' },
      { id: 'n11', title: '11', englishTitle: 'Eleven', image: '🔢', pronunciation: '/ɪˈlɛvən/' },
      { id: 'n12', title: '12', englishTitle: 'Twelve', image: '🔢', pronunciation: '/twɛlv/' },
      { id: 'n13', title: '13', englishTitle: 'Thirteen', image: '🔢', pronunciation: '/ˌθɜːrˈtiːn/' },
      { id: 'n14', title: '14', englishTitle: 'Fourteen', image: '🔢', pronunciation: '/ˌfɔːrˈtiːn/' },
      { id: 'n15', title: '15', englishTitle: 'Fifteen', image: '🔢', pronunciation: '/ˌfɪfˈtiːn/' },
      { id: 'n16', title: '16', englishTitle: 'Sixteen', image: '🔢', pronunciation: '/ˌsɪksˈtiːn/' },
      { id: 'n17', title: '17', englishTitle: 'Seventeen', image: '🔢', pronunciation: '/ˌsɛvənˈtiːn/' },
      { id: 'n18', title: '18', englishTitle: 'Eighteen', image: '🔢', pronunciation: '/ˌeɪˈtiːn/' },
      { id: 'n19', title: '19', englishTitle: 'Nineteen', image: '🔢', pronunciation: '/ˌnaɪnˈtiːn/' },
      { id: 'n20', title: '20', englishTitle: 'Twenty', image: '🔢', pronunciation: '/ˈtwɛnti/' },
    ]
  },
  {
    id: 'colors',
    icon: '🎨',
    title: '颜色',
    description: '学习常见颜色的英文名称',
    color: '#F39C12',
    type: 'vocab',
    items: [
      { id: 'cl01', title: '红色', englishTitle: 'Red', image: '🔴', pronunciation: '/rɛd/' },
      { id: 'cl02', title: '蓝色', englishTitle: 'Blue', image: '🔵', pronunciation: '/bluː/' },
      { id: 'cl03', title: '黄色', englishTitle: 'Yellow', image: '🟡', pronunciation: '/ˈjɛloʊ/' },
      { id: 'cl04', title: '绿色', englishTitle: 'Green', image: '🟢', pronunciation: '/ɡriːn/' },
      { id: 'cl05', title: '橙色', englishTitle: 'Orange', image: '🟠', pronunciation: '/ˈɔːrɪndʒ/' },
      { id: 'cl06', title: '紫色', englishTitle: 'Purple', image: '🟣', pronunciation: '/ˈpɜːrpəl/' },
      { id: 'cl07', title: '粉色', englishTitle: 'Pink', image: '🩷', pronunciation: '/pɪŋk/' },
      { id: 'cl08', title: '白色', englishTitle: 'White', image: '⚪', pronunciation: '/waɪt/' },
      { id: 'cl09', title: '黑色', englishTitle: 'Black', image: '⚫', pronunciation: '/blæk/' },
      { id: 'cl10', title: '灰色', englishTitle: 'Gray', image: '🩶', pronunciation: '/ɡreɪ/' },
      { id: 'cl11', title: '棕色', englishTitle: 'Brown', image: '🟤', pronunciation: '/braʊn/' },
      { id: 'cl12', title: '金色', englishTitle: 'Gold', image: '🥇', pronunciation: '/ɡoʊld/' },
    ]
  },
  {
    id: 'body',
    icon: '🧍',
    title: '身体部位',
    description: '学习身体各部位的英文名称',
    color: '#E74C3C',
    type: 'vocab',
    items: [
      { id: 'b01', title: '头', englishTitle: 'Head', image: '🗣️', pronunciation: '/hed/' },
      { id: 'b02', title: '眼睛', englishTitle: 'Eyes', image: '👀', pronunciation: '/aɪz/' },
      { id: 'b03', title: '耳朵', englishTitle: 'Ears', image: '👂', pronunciation: '/ɪrz/' },
      { id: 'b04', title: '鼻子', englishTitle: 'Nose', image: '👃', pronunciation: '/noʊz/' },
      { id: 'b05', title: '嘴巴', englishTitle: 'Mouth', image: '👄', pronunciation: '/maʊθ/' },
      { id: 'b06', title: '手', englishTitle: 'Hand', image: '✋', pronunciation: '/hænd/' },
      { id: 'b07', title: '脚', englishTitle: 'Foot', image: '🦶', pronunciation: '/fʊt/' },
      { id: 'b08', title: '腿', englishTitle: 'Leg', image: '🦵', pronunciation: '/leɡ/' },
      { id: 'b09', title: '胳膊', englishTitle: 'Arm', image: '💪', pronunciation: '/ɑːrm/' },
      { id: 'b10', title: '肚子', englishTitle: 'Stomach', image: '🫃', pronunciation: '/ˈstʌmək/' },
      { id: 'b11', title: '头发', englishTitle: 'Hair', image: '💇', pronunciation: '/her/' },
      { id: 'b12', title: '牙齿', englishTitle: 'Teeth', image: '🦷', pronunciation: '/tiːθ/' },
    ]
  },
  {
    id: 'clothes',
    icon: '👔',
    title: '衣物',
    description: '学习常见衣物的英文名称',
    color: '#8E44AD',
    type: 'vocab',
    items: [
      { id: 'c01', title: 'T恤', englishTitle: 'T-shirt', image: '👕', pronunciation: '/ˈtiːʃɜːrt/' },
      { id: 'c02', title: '裤子', englishTitle: 'Pants', image: '👖', pronunciation: '/pænts/' },
      { id: 'c03', title: '裙子', englishTitle: 'Dress', image: '👗', pronunciation: '/dres/' },
      { id: 'c04', title: '外套', englishTitle: 'Coat', image: '🧥', pronunciation: '/koʊt/' },
      { id: 'c05', title: '鞋子', englishTitle: 'Shoes', image: '👟', pronunciation: '/ʃuːz/' },
      { id: 'c06', title: '袜子', englishTitle: 'Socks', image: '🧦', pronunciation: '/sɒks/' },
      { id: 'c07', title: '帽子', englishTitle: 'Hat', image: '🧢', pronunciation: '/hæt/' },
      { id: 'c08', title: '手套', englishTitle: 'Gloves', image: '🧤', pronunciation: '/ɡlʌvz/' },
      { id: 'c09', title: '围巾', englishTitle: 'Scarf', image: '🧣', pronunciation: '/skɑːrf/' },
    ]
  },
  {
    id: 'greetings',
    icon: '👋',
    title: '日常用语',
    description: '日常问候和简单对话，点击就能听发音',
    color: '#FFD93D',
    type: 'vocab',
    items: [
      { id: 'g01', title: '你好', englishTitle: 'Hello', image: '👋', pronunciation: '/həˈloʊ/' },
      { id: 'g02', title: '早上好', englishTitle: 'Good Morning', image: '🌅', pronunciation: '/ɡʊd ˈmɔːrnɪŋ/' },
      { id: 'g03', title: '下午好', englishTitle: 'Good Afternoon', image: '☀️', pronunciation: '/ɡʊd ˌæftərˈnuːn/' },
      { id: 'g04', title: '晚上好', englishTitle: 'Good Evening', image: '🌆', pronunciation: '/ɡʊd ˈiːvnɪŋ/' },
      { id: 'g05', title: '晚安', englishTitle: 'Good Night', image: '🌙', pronunciation: '/ɡʊd naɪt/' },
      { id: 'g06', title: '谢谢', englishTitle: 'Thank You', image: '🙏', pronunciation: '/θæŋk juː/' },
      { id: 'g07', title: '对不起', englishTitle: 'Sorry', image: '😞', pronunciation: '/ˈsɒri/' },
      { id: 'g08', title: '再见', englishTitle: 'Goodbye', image: '👋', pronunciation: '/ɡʊdˈbaɪ/' },
      { id: 'g09', title: '请', englishTitle: 'Please', image: '🤝', pronunciation: '/pliːz/' },
      { id: 'g10', title: '没关系', englishTitle: "You're Welcome", image: '😊', pronunciation: '/jʊər ˈwɛlkəm/' },
      { id: 'g11', title: '是', englishTitle: 'Yes', image: '✅', pronunciation: '/jes/' },
      { id: 'g12', title: '不是', englishTitle: 'No', image: '❌', pronunciation: '/noʊ/' },
      { id: 'g13', title: '好的', englishTitle: 'OK', image: '👌', pronunciation: '/oʊˈkeɪ/' },
      { id: 'g14', title: '我也一样', englishTitle: 'Me Too', image: '🙋', pronunciation: '/miː tuː/' },
      { id: 'g15', title: '我不知道', englishTitle: "I Don't Know", image: '🤷', pronunciation: '/aɪ doʊnt noʊ/' },
      { id: 'g16', title: '等一下', englishTitle: 'Wait a Moment', image: '⏳', pronunciation: '/weɪt ə ˈmoʊmənt/' },
      { id: 'g17', title: '不客气', englishTitle: "You're Welcome", image: '🤗', pronunciation: '/jʊər ˈwɛlkəm/' },
      { id: 'g18', title: '打扰了', englishTitle: 'Excuse Me', image: '🙋‍♂️', pronunciation: '/ɪkˈskjuːz miː/' },
      { id: 'g19', title: '也', englishTitle: 'Also', image: '➕', pronunciation: '/ˈɔːlsoʊ/' },
      { id: 'g20', title: '也许', englishTitle: 'Maybe', image: '🤔', pronunciation: '/ˈmeɪbi/' },
      { id: 'g21', title: '当然', englishTitle: 'Of Course', image: '💯', pronunciation: '/əv kɔːrs/' },
      { id: 'g22', title: '没问题', englishTitle: 'No Problem', image: '👌', pronunciation: '/noʊ ˈprɒbləm/' },
      { id: 'g23', title: '太棒了', englishTitle: 'Awesome!', image: '🌟', pronunciation: '/ˈɔːsəm/' },
      { id: 'g24', title: '好极了', englishTitle: 'Excellent!', image: '⭐', pronunciation: '/ˈɛksələnt/' },
      { id: 'g25', title: '祝你好运', englishTitle: 'Good Luck!', image: '🍀', pronunciation: '/ɡʊd lʌk/' },
      { id: 'g26', title: '恭喜', englishTitle: 'Congratulations!', image: '🎊', pronunciation: '/kənˌɡrætʃəˈleɪʃənz/' },
    ]
  },
  {
    id: 'phrases',
    icon: '💬',
    title: '常用短句',
    description: '日常最常用的英语短句，学会就能开口说',
    color: '#9B59B6',
    type: 'vocab',
    items: [
      { id: 'p01', title: '我叫...', englishTitle: 'My name is...', image: '👦', pronunciation: '/maɪ neɪm ɪz/' },
      { id: 'p02', title: '你叫什么？', englishTitle: "What's your name?", image: '❓', pronunciation: '/wɒts jʊər neɪm/' },
      { id: 'p03', title: '我几岁了', englishTitle: "I'm ... years old", image: '🎂', pronunciation: '/aɪm ... jɪrz oʊld/' },
      { id: 'p04', title: '你几岁？', englishTitle: 'How old are you?', image: '🔢', pronunciation: '/haʊ oʊld ɑːr juː/' },
      { id: 'p05', title: '我很高兴', englishTitle: "I'm happy", image: '😊', pronunciation: '/aɪm ˈhæpi/' },
      { id: 'p06', title: '我很饿', englishTitle: "I'm hungry", image: '🍽️', pronunciation: '/aɪm ˈhʌŋɡri/' },
      { id: 'p07', title: '我累了', englishTitle: "I'm tired", image: '😴', pronunciation: '/aɪm taɪərd/' },
      { id: 'p08', title: '我渴了', englishTitle: "I'm thirsty", image: '🥤', pronunciation: '/aɪm ˈθɜːrsti/' },
      { id: 'p09', title: '这是我的', englishTitle: "It's mine", image: '☝️', pronunciation: '/ɪts maɪn/' },
      { id: 'p10', title: '给你', englishTitle: 'Here you are', image: '🤲', pronunciation: '/hɪr juː ɑːr/' },
      { id: 'p11', title: '我明白了', englishTitle: 'I see', image: '💡', pronunciation: '/aɪ siː/' },
      { id: 'p12', title: '让我来', englishTitle: 'Let me try', image: '💪', pronunciation: '/let miː traɪ/' },
      { id: 'p13', title: '太好了', englishTitle: 'Great!', image: '🎉', pronunciation: '/ɡreɪt/' },
      { id: 'p14', title: '小心', englishTitle: 'Be careful!', image: '⚠️', pronunciation: '/biː ˈkerfəl/' },
      { id: 'p15', title: '没关系', englishTitle: "It's OK", image: '👌', pronunciation: '/ɪts oʊˈkeɪ/' },
      { id: 'p16', title: '我喜欢', englishTitle: 'I like it', image: '❤️', pronunciation: '/aɪ laɪk ɪt/' },
      { id: 'p17', title: '我不喜欢', englishTitle: "I don't like it", image: '💔', pronunciation: '/aɪ doʊnt laɪk ɪt/' },
      { id: 'p18', title: '我想要', englishTitle: 'I want', image: '🤲', pronunciation: '/aɪ wɒnt/' },
      { id: 'p19', title: '我可以', englishTitle: 'I can', image: '💪', pronunciation: '/aɪ kæn/' },
      { id: 'p20', title: '这是啥', englishTitle: 'What is this?', image: '❓', pronunciation: '/wɒt ɪz ðɪs/' },
      { id: 'p21', title: '我能行', englishTitle: 'I can do it!', image: '✊', pronunciation: '/aɪ kæn duː ɪt/' },
      { id: 'p22', title: '加油', englishTitle: 'Come on!', image: '🔥', pronunciation: '/kʌm ɒn/' },
      { id: 'p23', title: '别担心', englishTitle: "Don't worry", image: '😌', pronunciation: '/doʊnt ˈwʌri/' },
      { id: 'p24', title: '我准备好了', englishTitle: "I'm ready", image: '🎯', pronunciation: '/aɪm ˈrɛdi/' },
      { id: 'p25', title: '我完成了', englishTitle: "I'm done!", image: '🏆', pronunciation: '/aɪm dʌn/' },
    ]
  },
  {
    id: 'school',
    icon: '🏫',
    title: '校园用语',
    description: '学校里常用的英语表达',
    color: '#3498DB',
    type: 'vocab',
    items: [
      { id: 's01', title: '上课了', englishTitle: 'Class begins', image: '🔔', pronunciation: '/klæs bɪˈɡɪnz/' },
      { id: 's02', title: '起立', englishTitle: 'Stand up', image: '🧍', pronunciation: '/stænd ʌp/' },
      { id: 's03', title: '坐下', englishTitle: 'Sit down', image: '🪑', pronunciation: '/sɪt daʊn/' },
      { id: 's04', title: '打开书', englishTitle: 'Open your book', image: '📖', pronunciation: '/ˈoʊpən jʊər bʊk/' },
      { id: 's05', title: '合上书', englishTitle: 'Close your book', image: '📕', pronunciation: '/kloʊz jʊər bʊk/' },
      { id: 's06', title: '听我说', englishTitle: 'Listen to me', image: '👂', pronunciation: '/ˈlɪsən tuː miː/' },
      { id: 's07', title: '跟我读', englishTitle: 'Read after me', image: '🗣️', pronunciation: '/riːd ˈæftər miː/' },
      { id: 's08', title: '写下来', englishTitle: 'Write it down', image: '✍️', pronunciation: '/raɪt ɪt daʊn/' },
      { id: 's09', title: '做作业', englishTitle: 'Do homework', image: '📝', pronunciation: '/duː ˈhoʊmwɜːrk/' },
      { id: 's10', title: '举手', englishTitle: 'Raise your hand', image: '✋', pronunciation: '/reɪz jʊər hænd/' },
      { id: 's11', title: '下课了', englishTitle: 'Class is over', image: '🎒', pronunciation: '/klæs ɪz ˈoʊvər/' },
      { id: 's12', title: '老师好', englishTitle: 'Hello, teacher', image: '👩‍🏫', pronunciation: '/həˈloʊ ˈtiːtʃər/' },
      { id: 's13', title: '考试', englishTitle: 'Test', image: '📋', pronunciation: '/tɛst/' },
      { id: 's14', title: '读书', englishTitle: 'Read a book', image: '📚', pronunciation: '/riːd ə bʊk/' },
      { id: 's15', title: '回答问题', englishTitle: 'Answer the question', image: '💡', pronunciation: '/ˈænsər ðə ˈkwɛstʃən/' },
      { id: 's16', title: '写字', englishTitle: 'Write', image: '✏️', pronunciation: '/raɪt/' },
      { id: 's17', title: '画画', englishTitle: 'Draw', image: '🎨', pronunciation: '/drɔː/' },
      { id: 's18', title: '唱歌', englishTitle: 'Sing', image: '🎤', pronunciation: '/sɪŋ/' },
      { id: 's19', title: '跳舞', englishTitle: 'Dance', image: '💃', pronunciation: '/dæns/' },
      { id: 's20', title: '玩游戏', englishTitle: 'Play a game', image: '🎮', pronunciation: '/pleɪ ə ɡeɪm/' },
    ]
  },
  {
    id: 'daily-sentences',
    icon: '🗣️',
    title: '日常对话',
    description: '生活中经常用到的英语对话',
    color: '#E67E22',
    type: 'vocab',
    items: [
      { id: 'd01', title: '你想吃什么？', englishTitle: 'What do you want to eat?', image: '🍔', pronunciation: '/wɒt duː juː wɒnt tuː iːt/' },
      { id: 'd02', title: '我要喝水', englishTitle: "I'd like some water", image: '💧', pronunciation: '/aɪd laɪk sʌm ˈwɔːtər/' },
      { id: 'd03', title: '我们去玩吧', englishTitle: "Let's go play!", image: '🎮', pronunciation: '/lets ɡoʊ pleɪ/' },
      { id: 'd04', title: '该睡觉了', englishTitle: "It's time to sleep", image: '🛏️', pronunciation: '/ɪts taɪm tuː sliːp/' },
      { id: 'd05', title: '洗手了没？', englishTitle: 'Did you wash your hands?', image: '🧼', pronunciation: '/dɪd juː wɒʃ jʊər hændz/' },
      { id: 'd06', title: '穿好衣服', englishTitle: 'Get dressed', image: '👕', pronunciation: '/ɡet drest/' },
      { id: 'd07', title: '出门了', englishTitle: "Let's go", image: '🚶', pronunciation: '/lets ɡoʊ/' },
      { id: 'd08', title: '我好冷', englishTitle: "I'm cold", image: '🥶', pronunciation: '/aɪm koʊld/' },
      { id: 'd09', title: '我好热', englishTitle: "I'm hot", image: '🥵', pronunciation: '/aɪm hɒt/' },
      { id: 'd10', title: '这是什么？', englishTitle: 'What is this?', image: '❓', pronunciation: '/wɒt ɪz ðɪs/' },
      { id: 'd11', title: '那是谁？', englishTitle: 'Who is that?', image: '👤', pronunciation: '/huː ɪz ðæt/' },
      { id: 'd12', title: '在哪里？', englishTitle: 'Where is it?', image: '📍', pronunciation: '/wer ɪz ɪt/' },
      { id: 'd13', title: '为什么？', englishTitle: 'Why?', image: '🤔', pronunciation: '/waɪ/' },
      { id: 'd14', title: '怎么样？', englishTitle: 'How?', image: '🔧', pronunciation: '/haʊ/' },
      { id: 'd15', title: '可以吗？', englishTitle: 'May I?', image: '🙏', pronunciation: '/meɪ aɪ/' },
      { id: 'd16', title: '几点了', englishTitle: 'What time is it?', image: '🕐', pronunciation: '/wɒt taɪm ɪz ɪt/' },
      { id: 'd17', title: '今天星期几', englishTitle: 'What day is today?', image: '📅', pronunciation: '/wɒt deɪ ɪz təˈdeɪ/' },
      { id: 'd18', title: '今天几号', englishTitle: "What's the date today?", image: '🗓️', pronunciation: '/wɒts ðə deɪt təˈdeɪ/' },
      { id: 'd19', title: '天气怎么样', englishTitle: "How's the weather?", image: '🌤️', pronunciation: '/haʊz ðə ˈwɛðər/' },
      { id: 'd20', title: '下雨了', englishTitle: "It's raining", image: '🌧️', pronunciation: '/ɪts ˈreɪnɪŋ/' },
      { id: 'd21', title: '太阳出来了', englishTitle: 'The sun is out', image: '☀️', pronunciation: '/ðə sʌn ɪz aʊt/' },
      { id: 'd22', title: '我要上厕所', englishTitle: 'I need to go to the bathroom', image: '🚻', pronunciation: '/aɪ niːd tuː ɡoʊ tuː ðə ˈbæθruːm/' },
      { id: 'd23', title: '我想回家', englishTitle: 'I want to go home', image: '🏠', pronunciation: '/aɪ wɒnt tuː ɡoʊ hoʊm/' },
      { id: 'd24', title: '我在学校', englishTitle: "I'm at school", image: '🏫', pronunciation: '/aɪm æt skuːl/' },
      { id: 'd25', title: '我在玩游戏', englishTitle: "I'm playing a game", image: '🎮', pronunciation: '/aɪm ˈpleɪɪŋ ə ɡeɪm/' },
    ]
  },
  {
    id: 'family-phrases',
    icon: '👨‍👩‍👧‍👦',
    title: '亲子对话',
    description: '家长和孩子之间的常用英语对话',
    color: '#1ABC9C',
    type: 'vocab',
    items: [
      { id: 'fp01', title: '我爱你', englishTitle: 'I love you', image: '❤️', pronunciation: '/aɪ lʌv juː/' },
      { id: 'fp02', title: '抱抱', englishTitle: 'Give me a hug', image: '🤗', pronunciation: '/ɡɪv miː ə hʌɡ/' },
      { id: 'fp03', title: '亲亲', englishTitle: 'Give me a kiss', image: '😘', pronunciation: '/ɡɪv miː ə kɪs/' },
      { id: 'fp04', title: '你真棒', englishTitle: 'You are great!', image: '👍', pronunciation: '/juː ɑːr ɡreɪt/' },
      { id: 'fp05', title: '做得好', englishTitle: 'Well done!', image: '👏', pronunciation: '/wel dʌn/' },
      { id: 'fp06', title: '不要哭', englishTitle: "Don't cry", image: '😢', pronunciation: '/doʊnt kraɪ/' },
      { id: 'fp07', title: '小心点', englishTitle: 'Watch out!', image: '👀', pronunciation: '/wɒtʃ aʊt/' },
      { id: 'fp08', title: '慢慢来', englishTitle: 'Take your time', image: '🐢', pronunciation: '/teɪk jʊər taɪm/' },
      { id: 'fp09', title: '再试一次', englishTitle: 'Try again', image: '🔄', pronunciation: '/traɪ əˈɡen/' },
      { id: 'fp10', title: '我帮你', englishTitle: "I'll help you", image: '🤝', pronunciation: '/aɪl help juː/' },
      { id: 'fp11', title: '听话', englishTitle: 'Be good', image: '😇', pronunciation: '/biː ɡʊd/' },
      { id: 'fp12', title: '快一点', englishTitle: 'Hurry up!', image: '⚡', pronunciation: '/ˈhʌri ʌp/' },
      { id: 'fp13', title: '吃饭了', englishTitle: "It's time to eat", image: '🍚', pronunciation: '/ɪts taɪm tuː iːt/' },
      { id: 'fp14', title: '该起床了', englishTitle: 'Time to get up', image: '⏰', pronunciation: '/taɪm tuː ɡet ʌp/' },
      { id: 'fp15', title: '今天在学校怎么样', englishTitle: 'How was school today?', image: '🏫', pronunciation: '/haʊ wɒz skuːl təˈdeɪ/' },
      { id: 'fp16', title: '做完作业了吗', englishTitle: 'Have you finished homework?', image: '📝', pronunciation: '/hæv juː ˈfɪnɪʃt ˈhoʊmwɜːrk/' },
      { id: 'fp17', title: '自己穿鞋', englishTitle: 'Put on your shoes', image: '👟', pronunciation: '/pʊt ɒn jʊər ʃuːz/' },
      { id: 'fp18', title: '刷牙洗脸', englishTitle: 'Brush your teeth and wash your face', image: '🪥', pronunciation: '/brʌʃ jʊər tiːθ ænd wɒʃ jʊər feɪs/' },
      { id: 'fp19', title: '收拾玩具', englishTitle: 'Clean up your toys', image: '🧸', pronunciation: '/kliːn ʌp jʊər tɔɪz/' },
      { id: 'fp20', title: '不要跑', englishTitle: "Don't run", image: '🚫', pronunciation: '/doʊnt rʌn/' },
    ]
  },
  {
    id: 'textbook',
    icon: '📖',
    title: '北京版二年级下册',
    description: '课本课文朗读和歌曲，6个单元',
    color: '#9B59B6',
    type: 'textbook',
    items: [
      { id: 't1r', title: '第1单元 朗读', englishTitle: 'Unit 1 Read', image: '📖', audio: '/audio/textbook/第1单元 read.mp3' },
      { id: 't1s', title: '第1单元 歌曲', englishTitle: 'Unit 1 Sing', image: '🎵', audio: '/audio/textbook/第1单元 sing.mp3' },
      { id: 't2r', title: '第2单元 朗读', englishTitle: 'Unit 2 Read', image: '📖', audio: '/audio/textbook/第2单元 read.mp3' },
      { id: 't2s', title: '第2单元 歌曲', englishTitle: 'Unit 2 Sing', image: '🎵', audio: '/audio/textbook/第2单元sing.mp3' },
      { id: 't3r', title: '第3单元 朗读', englishTitle: 'Unit 3 Read', image: '📖', audio: '/audio/textbook/第3单元 read.mp3' },
      { id: 't3s', title: '第3单元 歌曲', englishTitle: 'Unit 3 Sing', image: '🎵', audio: '/audio/textbook/第3单元sing.mp3' },
      { id: 't4r', title: '第4单元 朗读', englishTitle: 'Unit 4 Read', image: '📖', audio: '/audio/textbook/第4单元 read.mp3' },
      { id: 't4s', title: '第4单元 歌曲', englishTitle: 'Unit 4 Sing', image: '🎵', audio: '/audio/textbook/第4单元 sing.mp3' },
      { id: 't5r', title: '第5单元 朗读', englishTitle: 'Unit 5 Read', image: '📖', audio: '/audio/textbook/第5单元 read.mp3' },
      { id: 't5s', title: '第5单元 歌曲', englishTitle: 'Unit 5 Sing', image: '🎵', audio: '/audio/textbook/第5单元sing.mp3' },
      { id: 't6r', title: '第6单元 朗读', englishTitle: 'Unit 6 Read', image: '📖', audio: '/audio/textbook/第6单元 read.mp3' },
      { id: 't6s', title: '第6单元 歌曲', englishTitle: 'Unit 6 Sing', image: '🎵', audio: '/audio/textbook/第6单元 sing.mp3' },
    ]
  },
  {
    id: 'videos',
    icon: '🎬',
    title: '课文教学视频',
    description: '北京版二年级下册教学动画视频',
    color: '#E74C3C',
    type: 'video',
    items: [
      { id: 'vp1', title: 'P1 课文视频', image: '🎬', video: '/video/P1.mp4' },
      { id: 'vp2', title: 'P2 课文视频', image: '🎬', video: '/video/P2.mp4' },
      { id: 'vp9', title: 'P9 课文视频', image: '🎬', video: '/video/P9.mp4' },
      { id: 'vp10', title: 'P10 课文视频', image: '🎬', video: '/video/P10.mp4' },
      { id: 'vp12', title: 'P12 课文视频', image: '🎬', video: '/video/P12.mp4' },
      { id: 'vp17', title: 'P17 课文视频', image: '🎬', video: '/video/P17.mp4' },
      { id: 'vp18', title: 'P18 课文视频', image: '🎬', video: '/video/P18.mp4' },
      { id: 'vp20', title: 'P20 课文视频', image: '🎬', video: '/video/P20.mp4' },
    ]
  },
]

export const STORAGE_KEY = 'english-learning-app-data'
