import { LearningCategory, Achievement, UserData } from './types'

export const learningCategories: LearningCategory[] = [
  {
    id: 'animals',
    icon: '🦁',
    title: '动物篇',
    description: '学习44种动物的英文名称和科普知识',
    color: '#FF6B6B',
    type: 'vocab',
    items: [
      { id: 'a01', title: '猫', englishTitle: 'Cat', image: '🐱', pronunciation: '/kæt/', audio: '/audio/animals/【01-Cat全文】.mp3' },
      { id: 'a02', title: '狗', englishTitle: 'Dog', image: '🐶', pronunciation: '/dɔːɡ/', audio: '/audio/animals/【02-Dog全文】.mp3' },
      { id: 'a03', title: '长颈鹿', englishTitle: 'Giraffe', image: '🦒', pronunciation: '/dʒɪˈræf/', audio: '/audio/animals/【03-giraffe全文】.mp3' },
      { id: 'a04', title: '鲨鱼', englishTitle: 'Shark', image: '🦈', pronunciation: '/ʃɑːrk/', audio: '/audio/animals/【04-Shark全文】.mp3' },
      { id: 'a05', title: '青蛙', englishTitle: 'Frog', image: '🐸', pronunciation: '/frɒɡ/', audio: '/audio/animals/【05-frog1全文】.mp3' },
      { id: 'a06', title: '火烈鸟', englishTitle: 'Flamingo', image: '🦩', pronunciation: '/fləˈmɪŋɡoʊ/', audio: '/audio/animals/【06-flamingo全文】.mp3' },
      { id: 'a07', title: '鸡', englishTitle: 'Chicken', image: '🐔', pronunciation: '/ˈtʃɪkɪn/', audio: '/audio/animals/【07-Chicken全文】.mp3' },
      { id: 'a08', title: '鸵鸟', englishTitle: 'Ostrich', image: '🦤', pronunciation: '/ˈɒstrɪtʃ/', audio: '/audio/animals/【08-Ostrich全文】.mp3' },
      { id: 'a09', title: '鸭子', englishTitle: 'Duck', image: '🦆', pronunciation: '/dʌk/', audio: '/audio/animals/【09-duck全文】.mp3' },
      { id: 'a10', title: '小鸡', englishTitle: 'Chick', image: '🐥', pronunciation: '/tʃɪk/', audio: '/audio/animals/【10-chick全文】.mp3' },
      { id: 'a11', title: '河马', englishTitle: 'Hippo', image: '🦛', pronunciation: '/ˈhɪpoʊ/', audio: '/audio/animals/【11-hippo全文】.mp3' },
      { id: 'a12', title: '大象', englishTitle: 'Elephant', image: '🐘', pronunciation: '/ˈɛlɪfənt/', audio: '/audio/animals/【12-elephant全文】.mp3' },
      { id: 'a13', title: '鲸鱼', englishTitle: 'Whale', image: '🐋', pronunciation: '/weɪl/', audio: '/audio/animals/【13-whale全文】.mp3' },
      { id: 'a14', title: '犀牛', englishTitle: 'Rhino', image: '🦏', pronunciation: '/ˈraɪnoʊ/', audio: '/audio/animals/【14-rhino全文】.mp3' },
      { id: 'a15', title: '牛', englishTitle: 'Cow', image: '🐄', pronunciation: '/kaʊ/', audio: '/audio/animals/【15-cow全文】.mp3' },
      { id: 'a16', title: '兔子', englishTitle: 'Rabbit', image: '🐰', pronunciation: '/ˈræbɪt/', audio: '/audio/animals/【16-rabbit全文】.mp3' },
      { id: 'a17', title: '马', englishTitle: 'Horse', image: '🐴', pronunciation: '/hɔːrs/', audio: '/audio/animals/【17-horse全文】.mp3' },
      { id: 'a18', title: '鹅', englishTitle: 'Goose', image: '🪿', pronunciation: '/ɡuːs/', audio: '/audio/animals/【18-goose全文】.mp3' },
      { id: 'a19', title: '章鱼', englishTitle: 'Octopus', image: '🐙', pronunciation: '/ˈɒktəpəs/', audio: '/audio/animals/【19-octopus全文】.mp3' },
      { id: 'a20', title: '蚊子', englishTitle: 'Mosquito', image: '🦟', pronunciation: '/məˈskiːtoʊ/', audio: '/audio/animals/【20-mosquito全文】.mp3' },
      { id: 'a21', title: '熊猫', englishTitle: 'Panda', image: '🐼', pronunciation: '/ˈpændə/', audio: '/audio/animals/【21-Panda全文】.mp3' },
      { id: 'a22', title: '北极熊', englishTitle: 'Polar Bear', image: '🐻‍❄️', pronunciation: '/ˈpoʊlər ber/', audio: '/audio/animals/【22-polar bear】.mp3' },
      { id: 'a23', title: '企鹅', englishTitle: 'Penguin', image: '🐧', pronunciation: '/ˈpɛŋɡwɪn/', audio: '/audio/animals/【23-penguin全文】.mp3' },
      { id: 'a24', title: '猪', englishTitle: 'Pig', image: '🐷', pronunciation: '/pɪɡ/', audio: '/audio/animals/【24-pig全文】.mp3' },
      { id: 'a26', title: '老虎', englishTitle: 'Tiger', image: '🐯', pronunciation: '/ˈtaɪɡər/', audio: '/audio/animals/【26-tiger全文】.mp3' },
      { id: 'a27', title: '狮子', englishTitle: 'Lion', image: '🦁', pronunciation: '/ˈlaɪən/', audio: '/audio/animals/【27-狮子全文】.mp3' },
      { id: 'a28', title: '豹子', englishTitle: 'Leopard', image: '🐆', pronunciation: '/ˈlɛpərd/', audio: '/audio/animals/【28-豹子全文】.mp3' },
      { id: 'a30', title: '袋鼠', englishTitle: 'Kangaroo', image: '🦘', pronunciation: '/ˌkæŋɡəˈruː/', audio: '/audio/animals/【30-袋鼠全文】.mp3' },
      { id: 'a32', title: '蝴蝶', englishTitle: 'Butterfly', image: '🦋', pronunciation: '/ˈbʌtərflaɪ/', audio: '/audio/animals/【32-蝴蝶全文】.mp3' },
      { id: 'a33', title: '猴子', englishTitle: 'Monkey', image: '🐵', pronunciation: '/ˈmʌŋki/', audio: '/audio/animals/【33-猴子全文】.mp3' },
      { id: 'a34', title: '海龟', englishTitle: 'Sea Turtle', image: '🐢', pronunciation: '/siː ˈtɜːrtl/', audio: '/audio/animals/【34-海龟全文】.mp3' },
      { id: 'a36', title: '狼', englishTitle: 'Wolf', image: '🐺', pronunciation: '/wʊlf/', audio: '/audio/animals/【36-狼全文】.mp3' },
      { id: 'a37', title: '斑马', englishTitle: 'Zebra', image: '🦓', pronunciation: '/ˈziːbrə/', audio: '/audio/animals/【37-斑马全文】.mp3' },
      { id: 'a38', title: '猫头鹰', englishTitle: 'Owl', image: '🦉', pronunciation: '/aʊl/', audio: '/audio/animals/【38-猫头鹰全文】.mp3' },
      { id: 'a43', title: '考拉', englishTitle: 'Koala', image: '🐨', pronunciation: '/koʊˈɑːlə/', audio: '/audio/animals/【43-考拉全文】.mp3' },
    ]
  },
  {
    id: 'fruits',
    icon: '🍎',
    title: '果蔬篇',
    description: '学习36种水果蔬菜的英文名称和科普知识',
    color: '#4ECDC4',
    type: 'vocab',
    items: [
      { id: 'f01', title: '香蕉', englishTitle: 'Banana', image: '🍌', pronunciation: '/bəˈnænə/', audio: '/audio/fruits/【01-Banana全文】.mp3' },
      { id: 'f02', title: '西瓜', englishTitle: 'Watermelon', image: '🍉', pronunciation: '/ˈwɔːtərmelən/', audio: '/audio/fruits/【02-watermelon全文】.mp3' },
      { id: 'f03', title: '草莓', englishTitle: 'Strawberry', image: '🍓', pronunciation: '/ˈstrɔːberi/', audio: '/audio/fruits/【03-strawberry全文】.mp3' },
      { id: 'f04', title: '芒果', englishTitle: 'Mango', image: '🥭', pronunciation: '/ˈmæŋɡoʊ/', audio: '/audio/fruits/【04-mango全文】.mp3' },
      { id: 'f05', title: '葡萄', englishTitle: 'Grape', image: '🍇', pronunciation: '/ɡreɪp/', audio: '/audio/fruits/【05-grape全文】.mp3' },
      { id: 'f06', title: '柠檬', englishTitle: 'Lemon', image: '🍋', pronunciation: '/ˈlɛmən/', audio: '/audio/fruits/【6-lemon全文】.mp3' },
      { id: 'f07', title: '苹果', englishTitle: 'Apple', image: '🍎', pronunciation: '/ˈæpl/', audio: '/audio/fruits/【07-Apple全文】.mp3' },
      { id: 'f08', title: '蓝莓', englishTitle: 'Blueberry', image: '🫐', pronunciation: '/ˈbluːberi/', audio: '/audio/fruits/【08-blueberry全文】.mp3' },
      { id: 'f09', title: '菠萝', englishTitle: 'Pineapple', image: '🍍', pronunciation: '/ˈpaɪnæpl/', audio: '/audio/fruits/【09-pineapple全文】.mp3' },
      { id: 'f11', title: '樱桃', englishTitle: 'Cherry', image: '🍒', pronunciation: '/ˈtʃɛri/', audio: '/audio/fruits/【11-cherry全文】.mp3' },
      { id: 'f12', title: '桃子', englishTitle: 'Peach', image: '🍑', pronunciation: '/piːtʃ/', audio: '/audio/fruits/【12-peach全文】.mp3' },
      { id: 'f13', title: '橙子', englishTitle: 'Orange', image: '🍊', pronunciation: '/ˈɔːrɪndʒ/', audio: '/audio/fruits/【13-orange全文】.mp3' },
      { id: 'f14', title: '梨', englishTitle: 'Pear', image: '🍐', pronunciation: '/per/', audio: '/audio/fruits/【14-pear全文】.mp3' },
      { id: 'f16', title: '西兰花', englishTitle: 'Broccoli', image: '🥦', pronunciation: '/ˈbrɒkəli/', audio: '/audio/fruits/【16-broccoli全文】.mp3' },
      { id: 'f17', title: '黄瓜', englishTitle: 'Cucumber', image: '🥒', pronunciation: '/ˈkjuːkʌmbər/', audio: '/audio/fruits/【17-cucumber全文】.mp3' },
      { id: 'f18', title: '番茄', englishTitle: 'Tomato', image: '🍅', pronunciation: '/təˈmeɪtoʊ/', audio: '/audio/fruits/【18-tomato全文】.mp3' },
      { id: 'f19', title: '土豆', englishTitle: 'Potato', image: '🥔', pronunciation: '/pəˈteɪtoʊ/', audio: '/audio/fruits/【19-potato全文】.mp3' },
      { id: 'f23', title: '玉米', englishTitle: 'Corn', image: '🌽', pronunciation: '/kɔːrn/', audio: '/audio/fruits/【23-corn全文】.mp3' },
    ]
  },
  {
    id: 'vehicles',
    icon: '🚗',
    title: '车辆篇',
    description: '学习20种车辆的英文名称和科普知识',
    color: '#45B7D1',
    type: 'vocab',
    items: [
      { id: 'v01', title: '消防车', englishTitle: 'Fire Truck', image: '🚒', pronunciation: '/faɪr trʌk/', audio: '/audio/vehicles/【1-消防车全文】.mp3' },
      { id: 'v02', title: '救护车', englishTitle: 'Ambulance', image: '🚑', pronunciation: '/ˈæmbjələns/', audio: '/audio/vehicles/【2-救护车全文】.mp3' },
      { id: 'v03', title: '警车', englishTitle: 'Police Car', image: '🚔', pronunciation: '/pəˈliːs kɑːr/', audio: '/audio/vehicles/【3-警车全文】.mp3' },
      { id: 'v04', title: '挖掘机', englishTitle: 'Excavator', image: '🚜', pronunciation: '/ˈɛkskəveɪtər/', audio: '/audio/vehicles/【4-挖掘机全文】.mp3' },
      { id: 'v14', title: '飞机', englishTitle: 'Airplane', image: '✈️', pronunciation: '/ˈɛrpleɪn/', audio: '/audio/vehicles/【14-飞机全文】.mp3' },
      { id: 'v15', title: '高铁', englishTitle: 'High-speed Train', image: '🚄', pronunciation: '/haɪ spiːd treɪn/', audio: '/audio/vehicles/【15-高铁全文】.mp3' },
      { id: 'v16', title: '公交车', englishTitle: 'Bus', image: '🚌', pronunciation: '/bʌs/', audio: '/audio/vehicles/【16-公交车全文】.mp3' },
      { id: 'v17', title: '汽车', englishTitle: 'Car', image: '🚗', pronunciation: '/kɑːr/', audio: '/audio/vehicles/【17-汽车全文】.mp3' },
      { id: 'v20', title: '直升机', englishTitle: 'Helicopter', image: '🚁', pronunciation: '/ˈhɛlɪkɒptər/', audio: '/audio/vehicles/【20-直升机全文】.mp3' },
    ]
  },
  {
    id: 'textbook',
    icon: '📖',
    title: '北京版二年级下册',
    description: '课本课文朗读和歌曲，6个单元',
    color: '#9B59B6',
    type: 'textbook',
    items: [
      { id: 't1r', title: '第1单元 朗读', englishTitle: 'Unit 1 Read', image: '📖', audio: '/audio/textbook/第1单元 read.mp3' },
      { id: 't1s', title: '第1单元 歌曲', englishTitle: 'Unit 1 Sing', image: '🎵', audio: '/audio/textbook/第1单元 sing.mp3' },
      { id: 't2r', title: '第2单元 朗读', englishTitle: 'Unit 2 Read', image: '📖', audio: '/audio/textbook/第2单元 read.mp3' },
      { id: 't2s', title: '第2单元 歌曲', englishTitle: 'Unit 2 Sing', image: '🎵', audio: '/audio/textbook/第2单元sing.mp3' },
      { id: 't3r', title: '第3单元 朗读', englishTitle: 'Unit 3 Read', image: '📖', audio: '/audio/textbook/第3单元 read.mp3' },
      { id: 't3s', title: '第3单元 歌曲', englishTitle: 'Unit 3 Sing', image: '🎵', audio: '/audio/textbook/第3单元sing.mp3' },
      { id: 't4r', title: '第4单元 朗读', englishTitle: 'Unit 4 Read', image: '📖', audio: '/audio/textbook/第4单元 read.mp3' },
      { id: 't4s', title: '第4单元 歌曲', englishTitle: 'Unit 4 Sing', image: '🎵', audio: '/audio/textbook/第4单元 sing.mp3' },
      { id: 't5r', title: '第5单元 朗读', englishTitle: 'Unit 5 Read', image: '📖', audio: '/audio/textbook/第5单元 read.mp3' },
      { id: 't5s', title: '第5单元 歌曲', englishTitle: 'Unit 5 Sing', image: '🎵', audio: '/audio/textbook/第5单元sing.mp3' },
      { id: 't6r', title: '第6单元 朗读', englishTitle: 'Unit 6 Read', image: '📖', audio: '/audio/textbook/第6单元 read.mp3' },
      { id: 't6s', title: '第6单元 歌曲', englishTitle: 'Unit 6 Sing', image: '🎵', audio: '/audio/textbook/第6单元 sing.mp3' },
    ]
  },
  {
    id: 'videos',
    icon: '🎬',
    title: '课文教学视频',
    description: '北京版二年级下册教学动画视频',
    color: '#E74C3C',
    type: 'video',
    items: [
      { id: 'vp1', title: 'P1 课文视频', image: '🎬', video: '/video/P1.mp4' },
      { id: 'vp2', title: 'P2 课文视频', image: '🎬', video: '/video/P2.mp4' },
      { id: 'vp9', title: 'P9 课文视频', image: '🎬', video: '/video/P9.mp4' },
      { id: 'vp10', title: 'P10 课文视频', image: '🎬', video: '/video/P10.mp4' },
      { id: 'vp12', title: 'P12 课文视频', image: '🎬', video: '/video/P12.mp4' },
      { id: 'vp17', title: 'P17 课文视频', image: '🎬', video: '/video/P17.mp4' },
      { id: 'vp18', title: 'P18 课文视频', image: '🎬', video: '/video/P18.mp4' },
      { id: 'vp20', title: 'P20 课文视频', image: '🎬', video: '/video/P20.mp4' },
    ]
  },
  {
    id: 'pdf-materials',
    icon: '📄',
    title: '学习资料',
    description: '教材PDF、思维导图、亲子句子卡片',
    color: '#F39C12',
    type: 'pdf',
    items: [
      { id: 'pdf1', title: '北京版二年级英语下册教材', image: '📖', pdf: '/pdf/北京版二年级英语下册·新版教材.pdf', description: '完整课本教材' },
      { id: 'pdf2', title: '英语科普类思维导图102张', image: '🧠', pdf: '/pdf/科普类思维导图102张.pdf', description: '动物、果蔬、车辆思维导图' },
      { id: 'pdf3', title: '亲子英语句子卡片380个', image: '👨‍👩‍👧', pdf: '/pdf/亲子英语句子卡片（380个）.pdf', description: '日常亲子英语对话练习' },
    ]
  },
  {
    id: 'alphabet',
    icon: '🔤',
    title: '26个字母',
    description: '学习英文字母和发音，点击就能听',
    color: '#FF6B9D',
    type: 'vocab',
    items: [
      { id: 'la', title: 'A', englishTitle: 'Apple', image: '🍎', pronunciation: '/eɪ/' },
      { id: 'lb', title: 'B', englishTitle: 'Ball', image: '⚽', pronunciation: '/biː/' },
      { id: 'lc', title: 'C', englishTitle: 'Cat', image: '🐱', pronunciation: '/siː/' },
      { id: 'ld', title: 'D', englishTitle: 'Dog', image: '🐶', pronunciation: '/diː/' },
      { id: 'le', title: 'E', englishTitle: 'Egg', image: '🥚', pronunciation: '/iː/' },
      { id: 'lf', title: 'F', englishTitle: 'Fish', image: '🐠', pronunciation: '/ɛf/' },
      { id: 'lg', title: 'G', englishTitle: 'Green', image: '💚', pronunciation: '/dʒiː/' },
      { id: 'lh', title: 'H', englishTitle: 'House', image: '🏠', pronunciation: '/eɪtʃ/' },
      { id: 'li', title: 'I', englishTitle: 'Ice Cream', image: '🍦', pronunciation: '/aɪ/' },
      { id: 'lj', title: 'J', englishTitle: 'Jump', image: '🤸', pronunciation: '/dʒeɪ/' },
      { id: 'lk', title: 'K', englishTitle: 'King', image: '👑', pronunciation: '/keɪ/' },
      { id: 'll', title: 'L', englishTitle: 'Lion', image: '🦁', pronunciation: '/ɛl/' },
      { id: 'lm', title: 'M', englishTitle: 'Monkey', image: '🐵', pronunciation: '/ɛm/' },
      { id: 'ln', title: 'N', englishTitle: 'Nose', image: '👃', pronunciation: '/ɛn/' },
      { id: 'lo', title: 'O', englishTitle: 'Orange', image: '🍊', pronunciation: '/oʊ/' },
      { id: 'lp', title: 'P', englishTitle: 'Penguin', image: '🐧', pronunciation: '/piː/' },
      { id: 'lq', title: 'Q', englishTitle: 'Queen', image: '👸', pronunciation: '/kjuː/' },
      { id: 'lr', title: 'R', englishTitle: 'Rabbit', image: '🐰', pronunciation: '/ɑːr/' },
      { id: 'ls', title: 'S', englishTitle: 'Sun', image: '☀️', pronunciation: '/ɛs/' },
      { id: 'lt', title: 'T', englishTitle: 'Tiger', image: '🐯', pronunciation: '/tiː/' },
      { id: 'lu', title: 'U', englishTitle: 'Umbrella', image: '☂️', pronunciation: '/juː/' },
      { id: 'lv', title: 'V', englishTitle: 'Violin', image: '🎻', pronunciation: '/viː/' },
      { id: 'lw', title: 'W', englishTitle: 'Water', image: '💧', pronunciation: '/ˈdʌbəljuː/' },
      { id: 'lx', title: 'X', englishTitle: 'Xylophone', image: '🎵', pronunciation: '/ɛks/' },
      { id: 'ly', title: 'Y', englishTitle: 'Yellow', image: '💛', pronunciation: '/waɪ/' },
      { id: 'lz', title: 'Z', englishTitle: 'Zebra', image: '🦓', pronunciation: '/zɛd/' },
    ]
  },
  {
    id: 'greetings',
    icon: '👋',
    title: '日常用语',
    description: '日常问候和简单对话，点击就能听发音',
    color: '#FFD93D',
    type: 'vocab',
    items: [
      { id: 'g01', title: '你好', englishTitle: 'Hello', image: '👋', pronunciation: '/həˈloʊ/' },
      { id: 'g02', title: '早上好', englishTitle: 'Good Morning', image: '🌅', pronunciation: '/ɡʊd ˈmɔːrnɪŋ/' },
      { id: 'g03', title: '下午好', englishTitle: 'Good Afternoon', image: '☀️', pronunciation: '/ɡʊd ˌæftərˈnuːn/' },
      { id: 'g04', title: '晚上好', englishTitle: 'Good Evening', image: '🌆', pronunciation: '/ɡʊd ˈiːvnɪŋ/' },
      { id: 'g05', title: '晚安', englishTitle: 'Good Night', image: '🌙', pronunciation: '/ɡʊd naɪt/' },
      { id: 'g06', title: '谢谢', englishTitle: 'Thank You', image: '🙏', pronunciation: '/θæŋk juː/' },
      { id: 'g07', title: '对不起', englishTitle: 'Sorry', image: '😞', pronunciation: '/ˈsɒri/' },
      { id: 'g08', title: '再见', englishTitle: 'Goodbye', image: '👋', pronunciation: '/ɡʊdˈbaɪ/' },
      { id: 'g09', title: '请', englishTitle: 'Please', image: '🤝', pronunciation: '/pliːz/' },
      { id: 'g10', title: '没关系', englishTitle: "You're Welcome", image: '😊', pronunciation: '/jʊər ˈwɛlkəm/' },
      { id: 'g11', title: '是', englishTitle: 'Yes', image: '✅', pronunciation: '/jes/' },
      { id: 'g12', title: '不是', englishTitle: 'No', image: '❌', pronunciation: '/noʊ/' },
      { id: 'g13', title: '好的', englishTitle: 'OK', image: '👌', pronunciation: '/oʊˈkeɪ/' },
      { id: 'g14', title: '我也一样', englishTitle: 'Me Too', image: '🙋', pronunciation: '/miː tuː/' },
      { id: 'g15', title: '我不知道', englishTitle: "I Don't Know", image: '🤷', pronunciation: '/aɪ doʊnt noʊ/' },
      { id: 'g16', title: '等一下', englishTitle: 'Wait a Moment', image: '⏳', pronunciation: '/weɪt ə ˈmoʊmənt/' },
      { id: 'g17', title: '不客气', englishTitle: "You're Welcome", image: '🤗', pronunciation: '/jʊər ˈwɛlkəm/' },
      { id: 'g18', title: '打扰了', englishTitle: 'Excuse Me', image: '🙋‍♂️', pronunciation: '/ɪkˈskjuːz miː/' },
    ]
  },
  {
    id: 'phrases',
    icon: '💬',
    title: '常用短句',
    description: '日常最常用的英语短句，学会就能开口说',
    color: '#9B59B6',
    type: 'vocab',
    items: [
      { id: 'p01', title: '我叫...', englishTitle: 'My name is...', image: '👦', pronunciation: '/maɪ neɪm ɪz/' },
      { id: 'p02', title: '你叫什么？', englishTitle: "What's your name?", image: '❓', pronunciation: '/wɒts jʊər neɪm/' },
      { id: 'p03', title: '我几岁了', englishTitle: "I'm ... years old", image: '🎂', pronunciation: '/aɪm ... jɪrz oʊld/' },
      { id: 'p04', title: '你几岁？', englishTitle: 'How old are you?', image: '🔢', pronunciation: '/haʊ oʊld ɑːr juː/' },
      { id: 'p05', title: '我很高兴', englishTitle: "I'm happy", image: '😊', pronunciation: '/aɪm ˈhæpi/' },
      { id: 'p06', title: '我很饿', englishTitle: "I'm hungry", image: '🍽️', pronunciation: '/aɪm ˈhʌŋɡri/' },
      { id: 'p07', title: '我累了', englishTitle: "I'm tired", image: '😴', pronunciation: '/aɪm taɪərd/' },
      { id: 'p08', title: '我渴了', englishTitle: "I'm thirsty", image: '🥤', pronunciation: '/aɪm ˈθɜːrsti/' },
      { id: 'p09', title: '这是我的', englishTitle: "It's mine", image: '☝️', pronunciation: '/ɪts maɪn/' },
      { id: 'p10', title: '给你', englishTitle: 'Here you are', image: '🤲', pronunciation: '/hɪr juː ɑːr/' },
      { id: 'p11', title: '我明白了', englishTitle: 'I see', image: '💡', pronunciation: '/aɪ siː/' },
      { id: 'p12', title: '让我来', englishTitle: 'Let me try', image: '💪', pronunciation: '/let miː traɪ/' },
      { id: 'p13', title: '太好了', englishTitle: 'Great!', image: '🎉', pronunciation: '/ɡreɪt/' },
      { id: 'p14', title: '小心', englishTitle: 'Be careful!', image: '⚠️', pronunciation: '/biː ˈkerfəl/' },
      { id: 'p15', title: '没关系', englishTitle: "It's OK", image: '👌', pronunciation: '/ɪts oʊˈkeɪ/' },
    ]
  },
  {
    id: 'school',
    icon: '🏫',
    title: '校园用语',
    description: '学校里常用的英语表达',
    color: '#3498DB',
    type: 'vocab',
    items: [
      { id: 's01', title: '上课了', englishTitle: 'Class begins', image: '🔔', pronunciation: '/klæs bɪˈɡɪnz/' },
      { id: 's02', title: '起立', englishTitle: 'Stand up', image: '🧍', pronunciation: '/stænd ʌp/' },
      { id: 's03', title: '坐下', englishTitle: 'Sit down', image: '🪑', pronunciation: '/sɪt daʊn/' },
      { id: 's04', title: '打开书', englishTitle: 'Open your book', image: '📖', pronunciation: '/ˈoʊpən jʊər bʊk/' },
      { id: 's05', title: '合上书', englishTitle: 'Close your book', image: '📕', pronunciation: '/kloʊz jʊər bʊk/' },
      { id: 's06', title: '听我说', englishTitle: 'Listen to me', image: '👂', pronunciation: '/ˈlɪsən tuː miː/' },
      { id: 's07', title: '跟我读', englishTitle: 'Read after me', image: '🗣️', pronunciation: '/riːd ˈæftər miː/' },
      { id: 's08', title: '写下来', englishTitle: 'Write it down', image: '✍️', pronunciation: '/raɪt ɪt daʊn/' },
      { id: 's09', title: '做作业', englishTitle: 'Do homework', image: '📝', pronunciation: '/duː ˈhoʊmwɜːrk/' },
      { id: 's10', title: '举手', englishTitle: 'Raise your hand', image: '✋', pronunciation: '/reɪz jʊər hænd/' },
      { id: 's11', title: '下课了', englishTitle: 'Class is over', image: '🎒', pronunciation: '/klæs ɪz ˈoʊvər/' },
      { id: 's12', title: '老师好', englishTitle: 'Hello, teacher', image: '👩‍🏫', pronunciation: '/həˈloʊ ˈtiːtʃər/' },
    ]
  },
  {
    id: 'daily-sentences',
    icon: '🗣️',
    title: '日常对话',
    description: '生活中经常用到的英语对话',
    color: '#E67E22',
    type: 'vocab',
    items: [
      { id: 'd01', title: '你想吃什么？', englishTitle: 'What do you want to eat?', image: '🍔', pronunciation: '/wɒt duː juː wɒnt tuː iːt/' },
      { id: 'd02', title: '我要喝水', englishTitle: "I'd like some water", image: '💧', pronunciation: '/aɪd laɪk sʌm ˈwɔːtər/' },
      { id: 'd03', title: '我们去玩吧', englishTitle: "Let's go play!", image: '🎮', pronunciation: '/lets ɡoʊ pleɪ/' },
      { id: 'd04', title: '该睡觉了', englishTitle: "It's time to sleep", image: '🛏️', pronunciation: '/ɪts taɪm tuː sliːp/' },
      { id: 'd05', title: '洗手了没？', englishTitle: 'Did you wash your hands?', image: '🧼', pronunciation: '/dɪd juː wɒʃ jʊər hændz/' },
      { id: 'd06', title: '穿好衣服', englishTitle: 'Get dressed', image: '👕', pronunciation: '/ɡet drest/' },
      { id: 'd07', title: '出门了', englishTitle: "Let's go", image: '🚶', pronunciation: '/lets ɡoʊ/' },
      { id: 'd08', title: '我好冷', englishTitle: "I'm cold", image: '🥶', pronunciation: '/aɪm koʊld/' },
      { id: 'd09', title: '我好热', englishTitle: "I'm hot", image: '🥵', pronunciation: '/aɪm hɒt/' },
      { id: 'd10', title: '这是什么？', englishTitle: 'What is this?', image: '❓', pronunciation: '/wɒt ɪz ðɪs/' },
      { id: 'd11', title: '那是谁？', englishTitle: 'Who is that?', image: '👤', pronunciation: '/huː ɪz ðæt/' },
      { id: 'd12', title: '在哪里？', englishTitle: 'Where is it?', image: '📍', pronunciation: '/wer ɪz ɪt/' },
      { id: 'd13', title: '为什么？', englishTitle: 'Why?', image: '🤔', pronunciation: '/waɪ/' },
      { id: 'd14', title: '怎么样？', englishTitle: 'How?', image: '🔧', pronunciation: '/haʊ/' },
      { id: 'd15', title: '可以吗？', englishTitle: 'May I?', image: '🙏', pronunciation: '/meɪ aɪ/' },
    ]
  },
  {
    id: 'family-phrases',
    icon: '👨‍👩‍👧‍👦',
    title: '亲子对话',
    description: '家长和孩子之间的常用英语对话',
    color: '#1ABC9C',
    type: 'vocab',
    items: [
      { id: 'fp01', title: '我爱你', englishTitle: 'I love you', image: '❤️', pronunciation: '/aɪ lʌv juː/' },
      { id: 'fp02', title: '抱抱', englishTitle: 'Give me a hug', image: '🤗', pronunciation: '/ɡɪv miː ə hʌɡ/' },
      { id: 'fp03', title: '亲亲', englishTitle: 'Give me a kiss', image: '😘', pronunciation: '/ɡɪv miː ə kɪs/' },
      { id: 'fp04', title: '你真棒', englishTitle: 'You are great!', image: '👍', pronunciation: '/juː ɑːr ɡreɪt/' },
      { id: 'fp05', title: '做得好', englishTitle: 'Well done!', image: '👏', pronunciation: '/wel dʌn/' },
      { id: 'fp06', title: '不要哭', englishTitle: "Don't cry", image: '😢', pronunciation: '/doʊnt kraɪ/' },
      { id: 'fp07', title: '小心点', englishTitle: 'Watch out!', image: '👀', pronunciation: '/wɒtʃ aʊt/' },
      { id: 'fp08', title: '慢慢来', englishTitle: 'Take your time', image: '🐢', pronunciation: '/teɪk jʊər taɪm/' },
      { id: 'fp09', title: '再试一次', englishTitle: 'Try again', image: '🔄', pronunciation: '/traɪ əˈɡen/' },
      { id: 'fp10', title: '我帮你', englishTitle: "I'll help you", image: '🤝', pronunciation: '/aɪl help juː/' },
      { id: 'fp11', title: '听话', englishTitle: 'Be good', image: '😇', pronunciation: '/biː ɡʊd/' },
      { id: 'fp12', title: '快一点', englishTitle: 'Hurry up!', image: '⚡', pronunciation: '/ˈhʌri ʌp/' },
    ]
  },
  {
    id: 'body',
    icon: '🧍',
    title: '身体部位',
    description: '学习身体各部位的英文名称',
    color: '#E74C3C',
    type: 'vocab',
    items: [
      { id: 'b01', title: '头', englishTitle: 'Head', image: '🗣️', pronunciation: '/hed/' },
      { id: 'b02', title: '眼睛', englishTitle: 'Eyes', image: '👀', pronunciation: '/aɪz/' },
      { id: 'b03', title: '耳朵', englishTitle: 'Ears', image: '👂', pronunciation: '/ɪrz/' },
      { id: 'b04', title: '鼻子', englishTitle: 'Nose', image: '👃', pronunciation: '/noʊz/' },
      { id: 'b05', title: '嘴巴', englishTitle: 'Mouth', image: '👄', pronunciation: '/maʊθ/' },
      { id: 'b06', title: '手', englishTitle: 'Hand', image: '✋', pronunciation: '/hænd/' },
      { id: 'b07', title: '脚', englishTitle: 'Foot', image: '🦶', pronunciation: '/fʊt/' },
      { id: 'b08', title: '腿', englishTitle: 'Leg', image: '🦵', pronunciation: '/leɡ/' },
      { id: 'b09', title: '胳膊', englishTitle: 'Arm', image: '💪', pronunciation: '/ɑːrm/' },
      { id: 'b10', title: '肚子', englishTitle: 'Stomach', image: '🫃', pronunciation: '/ˈstʌmək/' },
      { id: 'b11', title: '头发', englishTitle: 'Hair', image: '💇', pronunciation: '/her/' },
      { id: 'b12', title: '牙齿', englishTitle: 'Teeth', image: '🦷', pronunciation: '/tiːθ/' },
    ]
  },
  {
    id: 'clothes',
    icon: '👔',
    title: '衣物',
    description: '学习常见衣物的英文名称',
    color: '#8E44AD',
    type: 'vocab',
    items: [
      { id: 'c01', title: 'T恤', englishTitle: 'T-shirt', image: '👕', pronunciation: '/ˈtiːʃɜːrt/' },
      { id: 'c02', title: '裤子', englishTitle: 'Pants', image: '👖', pronunciation: '/pænts/' },
      { id: 'c03', title: '裙子', englishTitle: 'Dress', image: '👗', pronunciation: '/dres/' },
      { id: 'c04', title: '外套', englishTitle: 'Coat', image: '🧥', pronunciation: '/koʊt/' },
      { id: 'c05', title: '鞋子', englishTitle: 'Shoes', image: '👟', pronunciation: '/ʃuːz/' },
      { id: 'c06', title: '袜子', englishTitle: 'Socks', image: '🧦', pronunciation: '/sɒks/' },
      { id: 'c07', title: '帽子', englishTitle: 'Hat', image: '🧢', pronunciation: '/hæt/' },
      { id: 'c08', title: '手套', englishTitle: 'Gloves', image: '🧤', pronunciation: '/ɡlʌvz/' },
      { id: 'c09', title: '围巾', englishTitle: 'Scarf', image: '🧣', pronunciation: '/skɑːrf/' },
    ]
  },
]

export const achievements: Achievement[] = [
  {
    id: 'first-checkin', name: '初出茅庐', description: '完成第一次打卡', icon: '🎯', level: 1,
    condition: (d: UserData) => d.totalCheckIns >= 1
  },
  {
    id: 'streak-3', name: '小有成就', description: '连续打卡3天', icon: '🔥', level: 1,
    condition: (d: UserData) => d.currentStreak >= 3
  },
  {
    id: 'streak-7', name: '坚持一周', description: '连续打卡7天', icon: '🔥🔥', level: 2,
    condition: (d: UserData) => d.currentStreak >= 7
  },
  {
    id: 'streak-30', name: '月度冠军', description: '连续打卡30天', icon: '⭐', level: 3,
    condition: (d: UserData) => d.currentStreak >= 30
  },
  {
    id: 'streak-100', name: '百日坚持', description: '连续打卡100天', icon: '🏆', level: 3,
    condition: (d: UserData) => d.currentStreak >= 100
  },
  {
    id: 'study-1hour', name: '初尝学习', description: '累计学习1小时', icon: '📚', level: 1,
    condition: (d: UserData) => d.totalLearningMinutes >= 60
  },
  {
    id: 'study-5hours', name: '学习使者', description: '累计学习5小时', icon: '📚📚', level: 2,
    condition: (d: UserData) => d.totalLearningMinutes >= 300
  },
  {
    id: 'study-20hours', name: '学习达人', description: '累计学习20小时', icon: '📚📚📚', level: 2,
    condition: (d: UserData) => d.totalLearningMinutes >= 1200
  },
  {
    id: 'checkin-10', name: '十次打卡', description: '累计打卡10次', icon: '✅', level: 1,
    condition: (d: UserData) => d.totalCheckIns >= 10
  },
  {
    id: 'checkin-50', name: '五十次打卡', description: '累计打卡50次', icon: '✅✅', level: 2,
    condition: (d: UserData) => d.totalCheckIns >= 50
  },
  {
    id: 'checkin-100', name: '百次打卡', description: '累计打卡100次', icon: '✅✅✅', level: 3,
    condition: (d: UserData) => d.totalCheckIns >= 100
  },
]

export const STORAGE_KEY = 'english-learning-app-data'
